version: 2.1
orbs:
  node: circleci/node@4.9.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      
      - run:
          name: FE Install
          command: |
            npm run fe:install
      - run:
          name: BE Install
          command: |
            npm run be:install
      - run:
          name: FE Build
          command: |
            npm run fe:build
      - run:
          name: BE Build
          command: |
            npm run be:build
      - run:
          name: FE Deploy App
          command: |
            npm run fe:deploy
      - run:
          name: BE Deploy App
          command: |
            npm run be:deploy